FROM docker.io/library/openjdk:18-alpine

LABEL maintainer="louis@orleans.io"

# user-configurable vars
ENV EULA false
ENV RAM_MAX 8G

ENV JAR_DIR /server-jars

COPY src/java/entrypoint.sh /
COPY src/java/download.py /
COPY requirements.txt /

VOLUME /data
VOLUME /server-jars

WORKDIR /data

EXPOSE 25565
# RCON port
EXPOSE 25575

RUN apk add python3 py3-pip && \
  python3 -m pip install -r /requirements.txt

COPY src/java/Containerfile /
COPY LICENSE /
COPY README.md /

COPY --from=mcrcon_mcrcon /mcrcon .

ENTRYPOINT /entrypoint.sh

HEALTHCHECK CMD mcstatus localhost status || exit 1
