ARG MCRCON_IMAGE=mcrcon
FROM ${MCRCON_IMAGE} as mcrcon

FROM docker.io/library/openjdk:17-slim

LABEL maintainer="louis@orleans.io"

# user-configurable vars
ENV EULA false
ENV RAM_MAX 8G

ENV JAR_DIR /server-jars

VOLUME /data
VOLUME /server-jars

# Game port
EXPOSE 25565
# RCON port
EXPOSE 25575

WORKDIR /mc-server

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y \
    git \
    python3 \
    python3-pip \
    wget \
  && \
  python3 -m pip install \
    requests

COPY src/servers/papermc/entrypoint.sh /
COPY src/servers/papermc/download.py /
COPY src/scripts/mc_utils.py /

COPY src/servers/papermc/Containerfile /
COPY LICENSE /
COPY README.md /

COPY --from=mcrcon /mcrcon .
ENV MCRCON_HOST localhost
ENV MCRCON_PORT 25575

RUN addgroup --gid 1001 minecraft && \
  adduser --uid 1000 --gid 1001 --disabled-password minecraft
USER minecraft

WORKDIR /data

ENTRYPOINT /entrypoint.sh
# ENTRYPOINT PYTHONPATH=/ python3 -c "import mc_utils; print(mc_utils.get_java_args('$RAM_MAX'))"

HEALTHCHECK CMD /mcrcon 'list' || exit 1
