name: Publish Docker

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    # tags:
    #   - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          for image in mcrcon $(ls src/servers); do
            docker build -f "src/$image/Containerfile" -t "$image" .
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Registry
        run: |
          REPO="ghcr.io/$( \
            echo ${{ github.repository }} | \
            tr '[:upper:]' '[:lower:]' | \
            sed 's/docker-//' \
          )"
          BRANCH=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$BRANCH

          echo "REPO = $REPO"
          echo "VERSION = $VERSION"

          for image in mcrcon $(ls src/servers); do
            docker tag "$image" "$REPO/$image:$VERSION"
            docker push "$REPO/$image:$VERSION"

            # Use Docker `latest` tag convention
            if [[ "(master|main)" =~ "$BRANCH" ]]; then
              docker tag "$image" "$REPO/$image:latest"
              docker push "$REPO/$image:latest"
            fi
          done
